### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by raphaelauv** [mapbox/osrm-isochrone#30]
hi , i'm very new in javascript and nodejs environnement
i can't install osrm-isochrone ( if you have a docker version , that would be perfect )

```
npm WARN deprecated @turf/inside@3.14.0: Module has been renamed to @turf/boolean-point-in-polygon

> osrm@5.18.0 install /home/myname/repositories/toto/node_modules/osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.18.0/Release/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/myname/repositories/toto/node_modules/osrm/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/myname/repositories/toto/node_modules/osrm/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:432:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Linux 4.13.0-46-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/raphael/repositories/toto/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/myname/repositories/toto/node_modules/osrm
node-pre-gyp ERR! node -v v10.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.18.0/Release/node-v64-linux-x64.tar.gz
Needs cmake to build from source
npm WARN enoent ENOENT: no such file or directory, open '/home/myname/repositories/toto/package.json'
npm WARN toto No description
npm WARN toto No repository field.
npm WARN toto No README data
npm WARN toto No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osrm@5.18.0 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the osrm@5.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myname/.npm/_logs/2018-08-17T12_36_19_171Z-debug.log
```

could you please help me , thank you

**Comment by mvl22** [comment]
According to https://github.com/Project-OSRM/osrm-backend/issues/4940#issuecomment-371180588:

"We do not yet support NodeJS 9.x, please downgrade to 8.x LTS."

So switch to Node.js 8:

`nvm install 8 && nvm use 8`

then retry.
