### ISSUE TITLE
Error: .geometry not found

### ISSUE THREAD

**Issue by MichailKachalov** [mapbox/osrm-isochrone#6]
When execute "Usage example", recived error:

/usr/lib/node_modules/osrm-isochrone/index.js:11
    var osrm = new OSRM(network);
               ^
Error: .geometry not found
    at module.exports (/usr/lib/node_modules/osrm-isochrone/index.js:11:16)
    at Object.<anonymous> (/usr/lib/node_modules/osrm-isochrone/test1/test.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

-----------
latest osrm-prepare not generate file .geometry, for success need use osrm-extract and osrm-prepare placed in Node.js osrm module

**Comment by Yetzederixx** [comment]
I had a similar problem, but with .hgsr file, and had to manually compile the osrm-backend project and use those executables.

**Comment by TheMarex** [comment]
> latest osrm-prepare not generate file .geometry, for success need use osrm-extract and osrm-prepare placed in Node.js osrm module

README should make this more clear now.
